name: test_env_vars

on:
  push:

jobs:
  test_env_vars:
    runs-on: ubuntu-20.04
    steps:
      - name: env vars
        env:
          VERSION: ${GITHUB_REF##*/}
        run: |
          echo ${GITHUB_REF##*/}
          echo ${VERSION}
          echo ${VERSION%.*}

      - name: env vars second try
        env:
          VERSION: ${GITHUB_REF##*/}
        run: |
          cat ${GITHUB_ENV}
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "MAJOR_MINOR_VERSION=${VERSION%.*}" >> $GITHUB_ENV
      - name: read env
        run: |
          cat ${GITHUB_ENV}
          echo $VERSION
          echo ${VERSION%.*}
          echo $MAJOR_MINOR_VERSION
