name: test_env_vars

on:
  push:

jobs:
  test_env_vars:
    runs-on: ubuntu-20.04
    env:
      VERSION: ${GITHUB_REF##*/}
      MAJOR_MINOR_VERSION: ${VERSION%.*}
    steps:
      - name: env vars
        run: |
          echo ${{ GITHUB_REF##*/ }}
          echo ${{ env.VERSION }}
          echo ${{ env.MAJOR_MINOR_VERSION }}
