name: test_env_vars

on:
  push:

jobs:
  test_env_vars:
    runs-on: ubuntu-20.04
    steps:
      - name: env vars
        env:
          VERSION: ${GITHUB_REF##*/}
        run: |
          echo ${GITHUB_REF##*/}
          echo ${VERSION}
          echo ${VERSION%.*}
